metadata:
  name: Testing
  short_name: Test
  description: None
  language: pt
  url: 'http://localhost'
  pathPrefix: /
  gaTrackingId: null
  favicon: /assets/favicon.png
  themeColor: '#0066cc'
header:
  enabled: true
  logo: /assets/logo.png
  links: []
sidebar:
  ignoreIndex: false
  forcedNavOrder: []
  expanded: []
  groups: []
  links: []
  poweredBy: {}
  enabled: true
pwa:
  enabled: true
  manifest:
    icon: /assets/logo.png
    display: minimal-ui
    crossOrigin: anonymous
features:
  editOnRepo:
    editable: true
    location: ''
    type: __none
  search:
    enabled: true,
    engine: 'localsearch'
    localSearchEngine: 'balance'
    excerptSize: 10000
    placeholder: 'Pesquisar...'
    startComponent: 'input'
    debounceTime: 380,
    snippetLength: 22,
    hitsPerPage: 10,
    showStats: true,
    pagination:
      enabled: true,
      totalPages: 10,
      showNext: false,
      showPrevious: false
  rss:
    enabled: false
    showIcon: false
    copyright: ''
    categories: []
    matchRegex: ^/
    outputPath: /rss.xml
  darkMode:
    enabled: true
    default: false
search:
  enabled: true
  startComponent: input
  placeholder: Procure algo...
  pagination:
    enabled: true
